In [ ]:
#Importing Labraries
import pandas as pd
import numpy as np

In [ ]:
#uploading/Reading Dataset
df = pd.read_csv('/content/sample_data/diabetic_data.csv')

In [ ]:
df.head(6)

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
5,35754,82637451,Caucasian,Male,[50-60),?,2,1,2,3,...,No,Steady,No,No,No,No,No,No,Yes,>30

In [ ]:
df.replace("?", np.nan, inplace=True)

In [ ]:
df.shape

(101766, 50)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      99493 non-null   object
 3   gender                    101766 non-null  object
 4   age                       101766 non-null  object
 5   weight                    3197 non-null    object
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                61510 non-null   object
 11  medical_specialty         51817 non-null   object
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101745 non-null  object
 19  diag_2                    101408 non-null  object
 20  diag_3                    100343 non-null  object
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             5346 non-null    object
 23  A1Cresult                 17018 non-null   object
 24  metformin                 101766 non-null  object
 25  repaglinide               101766 non-null  object
 26  nateglinide               101766 non-null  object
 27  chlorpropamide            101766 non-null  object
 28  glimepiride               101766 non-null  object
 29  acetohexamide             101766 non-null  object
 30  glipizide                 101766 non-null  object
 31  glyburide                 101766 non-null  object
 32  tolbutamide               101766 non-null  object
 33  pioglitazone              101766 non-null  object
 34  rosiglitazone             101766 non-null  object
 35  acarbose                  101766 non-null  object
 36  miglitol                  101766 non-null  object
 37  troglitazone              101766 non-null  object
 38  tolazamide                101766 non-null  object
 39  examide                   101766 non-null  object
 40  citoglipton               101766 non-null  object
 41  insulin                   101766 non-null  object
 42  glyburide-metformin       101766 non-null  object
 43  glipizide-metformin       101766 non-null  object
 44  glimepiride-pioglitazone  101766 non-null  object
 45  metformin-rosiglitazone   101766 non-null  object
 46  metformin-pioglitazone    101766 non-null  object
 47  change                    101766 non-null  object
 48  diabetesMed               101766 non-null  object
 49  readmitted                101766 non-null  object
dtypes: int64(13), object(37)
memory usage: 38.8+ MB

In [ ]:
df.isnull().sum().sort_values(ascending=False)

weight                      98569
max_glu_serum               96420
A1Cresult                   84748
medical_specialty           49949
payer_code                  40256
race                         2273
diag_3                       1423
diag_2                        358
diag_1                         21
patient_nbr                     0
time_in_hospital                0
admission_source_id             0
num_lab_procedures              0
encounter_id                    0
admission_type_id               0
discharge_disposition_id        0
gender                          0
age                             0
number_inpatient                0
number_emergency                0
number_outpatient               0
num_medications                 0
num_procedures                  0
number_diagnoses                0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [ ]:
df.describe()

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,1.017660e+05,1.017660e+05,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000
mean,1.652016e+08,5.433040e+07,2.024006,3.715642,5.754437,4.395987,43.095641,1.339730,16.021844,0.369357,0.197836,0.635566,7.422607
std,1.026403e+08,3.869636e+07,1.445403,5.280166,4.064081,2.985108,19.674362,1.705807,8.127566,1.267265,0.930472,1.262863,1.933600
min,1.252200e+04,1.350000e+02,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,8.496119e+07,2.341322e+07,1.000000,1.000000,1.000000,2.000000,31.000000,0.000000,10.000000,0.000000,0.000000,0.000000,6.000000
50%,1.523890e+08,4.550514e+07,1.000000,1.000000,7.000000,4.000000,44.000000,1.000000,15.000000,0.000000,0.000000,0.000000,8.000000
75%,2.302709e+08,8.754595e+07,3.000000,4.000000,7.000000,6.000000,57.000000,2.000000,20.000000,0.000000,0.000000,1.000000,9.000000
max,4.438672e+08,1.895026e+08,8.000000,28.000000,25.000000,14.000000,132.000000,6.000000,81.000000,42.000000,76.000000,21.000000,16.000000

In [ ]:
df["readmitted"].value_counts()

readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

In [ ]:
df["age"].value_counts()

age
[70-80)     26068
[60-70)     22483
[50-60)     17256
[80-90)     17197
[40-50)      9685
[30-40)      3775
[90-100)     2793
[20-30)      1657
[10-20)       691
[0-10)        161
Name: count, dtype: int64

In [ ]:
df["gender"].value_counts()

gender
Female             54708
Male               47055
Unknown/Invalid        3
Name: count, dtype: int64

In [ ]:
df.drop(columns=["weight","payer_code","medical_specialty","patient_nbr", "diag_1","diag_2", "diag_3","max_glu_serum",
        "A1Cresult","metformin","repaglinide","nateglinide","chlorpropamide",
        "glimepiride","acetohexamide","glipizide","glyburide", "tolbutamide",
        "pioglitazone","rosiglitazone","acarbose","miglitol","troglitazone",
        "tolazamide","examide","citoglipton","insulin","glyburide-metformin",
        "glipizide-metformin","glimepiride-pioglitazone","metformin-rosiglitazone",
        "metformin-pioglitazone","change","diabetesMed"],
    inplace=True)

In [ ]:
df = df[df["gender"] != "Unknown/Invalid"]

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
missing_values = df.isnull().sum()

In [ ]:
df.columns = df.columns.str.lower()

In [ ]:
df.head(6)

,encounter_id,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses,readmitted
0,2278392,Caucasian,Female,[0-10),6,25,1,1,41,0,1,0,0,0,1,NO
1,149190,Caucasian,Female,[10-20),1,1,7,3,59,0,18,0,0,0,9,>30
2,64410,AfricanAmerican,Female,[20-30),1,1,7,2,11,5,13,2,0,1,6,NO
3,500364,Caucasian,Male,[30-40),1,1,7,2,44,1,16,0,0,0,7,NO
4,16680,Caucasian,Male,[40-50),1,1,7,1,51,0,8,0,0,0,5,NO
5,35754,Caucasian,Male,[50-60),2,1,2,3,31,6,16,0,0,0,9,>30

In [ ]:
df.shape

(101763, 16)

In [ ]:
df.columns.tolist()

['encounter_id',
 'race',
 'gender',
 'age',
 'admission_type_id',
 'discharge_disposition_id',
 'admission_source_id',
 'time_in_hospital',
 'num_lab_procedures',
 'num_procedures',
 'num_medications',
 'number_outpatient',
 'number_emergency',
 'number_inpatient',
 'number_diagnoses',
 'readmitted']

# Feature Engineering

In [ ]:
df["readmission_30_days"] = np.where(
    df["readmitted"] == "<30",1,0)

In [ ]:
df["total_prior_visits"] = (
    df["number_inpatient"] +
    df["number_outpatient"] +
    df["number_emergency"])

In [ ]:
df["long_stay"] = np.where(
    df["time_in_hospital"] >= 7,1,0)

In [ ]:
df["polypharmacy"] = np.where(
    df["num_medications"] >= 10,1,0)

In [ ]:
df["high_utilizer"] = np.where(
    df["total_prior_visits"] >= 5,1,0)

In [ ]:
#Final Checking

df.shape

(101763, 21)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 101763 entries, 0 to 101765
Data columns (total 21 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101763 non-null  int64
 1   race                      99492 non-null   object
 2   gender                    101763 non-null  object
 3   age                       101763 non-null  object
 4   admission_type_id         101763 non-null  int64
 5   discharge_disposition_id  101763 non-null  int64
 6   admission_source_id       101763 non-null  int64
 7   time_in_hospital          101763 non-null  int64
 8   num_lab_procedures        101763 non-null  int64
 9   num_procedures            101763 non-null  int64
 10  num_medications           101763 non-null  int64
 11  number_outpatient         101763 non-null  int64
 12  number_emergency          101763 non-null  int64
 13  number_inpatient          101763 non-null  int64
 14  number_diagnoses          101763 non-null  int64
 15  readmitted                101763 non-null  object
 16  readmission_30_days       101763 non-null  int64
 17  total_prior_visits        101763 non-null  int64
 18  long_stay                 101763 non-null  int64
 19  polypharmacy              101763 non-null  int64
 20  high_utilizer             101763 non-null  int64
dtypes: int64(17), object(4)
memory usage: 17.1+ MB

In [ ]:
df.isnull().sum().sort_values(ascending=False)

race                        2271
encounter_id                   0
gender                         0
age                            0
admission_type_id              0
discharge_disposition_id       0
admission_source_id            0
time_in_hospital               0
num_lab_procedures             0
num_procedures                 0
num_medications                0
number_outpatient              0
number_emergency               0
number_inpatient               0
number_diagnoses               0
readmitted                     0
readmission_30_days            0
total_prior_visits             0
long_stay                      0
polypharmacy                   0
high_utilizer                  0
dtype: int64

In [ ]:
df["race"] = df["race"].fillna("Unknown")

In [ ]:
df.isnull().sum().sort_values(ascending=False)

encounter_id                0
race                        0
gender                      0
age                         0
admission_type_id           0
discharge_disposition_id    0
admission_source_id         0
time_in_hospital            0
num_lab_procedures          0
num_procedures              0
num_medications             0
number_outpatient           0
number_emergency            0
number_inpatient            0
number_diagnoses            0
readmitted                  0
readmission_30_days         0
total_prior_visits          0
long_stay                   0
polypharmacy                0
high_utilizer               0
dtype: int64

In [ ]:
df.to_csv('Diabetic_Data_clean.csv' , index=False)

In [ ]:
from google.colab import files
files.download('Diabetic_Data_clean.csv')